#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: root
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: emailsender_db

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: YOUR_EMAIL
EMAIL_PASSWORD: YOUR_PASSWORD
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
